### ISSUE TITLE
交叉编译时出现error: 'for' loop initial declarations are only allowed in C99 mode报错时

### ISSUE THREAD

**Issue by hengle92** [FurryAcetylCoA/sguclient#18]
将\sguclient\src\dprotocol.c中的for循环内定义i变量改为在外定义i变量
![DLN1W9CGZQL~07V4%`GQ3U8](https://user-images.githubusercontent.com/79264847/161268036-926c0a8c-bf98-4310-a9fa-b54d97a34491.png)
![R1CXY_@G7 $22OZ{%P)C6Z8](https://user-images.githubusercontent.com/79264847/161268050-13269575-faed-4c38-a723-53cf5dd67d8a.png)

**Comment by IDeLoveYou** [comment]
可以直接在sguclient/makefile里加入TARGET_CFLAGS += -std=gnu99
